"""empty message

Revision ID: 399fbceb5e07
Revises: 67ef4e48d0e3
Create Date: 2025-07-01 12:58:34.027095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '399fbceb5e07'
down_revision = '67ef4e48d0e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.Text(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('difficulty')

    # ### end Alembic commands ###
