"""empty message

Revision ID: 47ca44cee62a
Revises: 
Create Date: 2025-06-26 12:42:25.749059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47ca44cee62a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('fitness_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_protein', sa.Integer(), nullable=True),
    sa.Column('daily_carbohydrates', sa.Integer(), nullable=True),
    sa.Column('daily_fat', sa.Integer(), nullable=True),
    sa.Column('daily_fiber', sa.Integer(), nullable=True),
    sa.Column('daily_calories', sa.Integer(), nullable=True),
    sa.Column('allergy', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredients', sa.Text(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('cooking_time', sa.Integer(), nullable=True),
    sa.Column('prep_time', sa.Integer(), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=True),
    sa.Column('protein_amount', sa.Integer(), nullable=True),
    sa.Column('carb_amount', sa.Integer(), nullable=True),
    sa.Column('fiber_amount', sa.Integer(), nullable=True),
    sa.Column('fat_amount', sa.Integer(), nullable=True),
    sa.Column('calorie_amount', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes')
    op.drop_table('fitness_goals')
    op.drop_table('users')
    # ### end Alembic commands ###
