"""empty message

Revision ID: da58f81d9fc7
Revises: 399fbceb5e07
Create Date: 2025-07-08 16:43:38.819856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da58f81d9fc7'
down_revision = '399fbceb5e07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_protein', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_carbohydrates', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_fat', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_fiber', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_calories', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('current_calories')
        batch_op.drop_column('current_fiber')
        batch_op.drop_column('current_fat')
        batch_op.drop_column('current_carbohydrates')
        batch_op.drop_column('current_protein')

    # ### end Alembic commands ###
